name: Deploy

on:
  push:
    branches: [ main ]

jobs:   
  deploy_to_dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v2
      - name: Set Env Variable - D365:Url
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api: https://api.london.cloud.service.gov.uk
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: dfe
          cf_space: academy-transfers
          command: set-env academy-transfers-api D365:Url ${{ secrets.D365_Url }}
      - name: Set Env Variable - D365:ClientId
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api: https://api.london.cloud.service.gov.uk
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: dfe
          cf_space: academy-transfers
          command: set-env academy-transfers-api D365:ClientId ${{ secrets.D365_ClientId }}
      - name: Set Env Variable - D365:ClientSecret
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api: https://api.london.cloud.service.gov.uk
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: dfe
          cf_space: academy-transfers
          command: set-env academy-transfers-api D365:ClientSecret ${{ secrets.D365_ClientSecret }}
      - name: Set Env Variable - AAD:Instance
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api: https://api.london.cloud.service.gov.uk
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: dfe
          cf_space: academy-transfers
          command: set-env academy-transfers-api AAD:Instance ${{ secrets.AAD_INSTANCE }}
      - name: Set Env Variable - AAD:ResourceId
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api: https://api.london.cloud.service.gov.uk
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: dfe
          cf_space: academy-transfers
          command: set-env academy-transfers-api AAD:ResourceId ${{ secrets.AAD_ResourceId }}
      - name: Set Env Variable - AAD:TenantId
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api: https://api.london.cloud.service.gov.uk
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: dfe
          cf_space: academy-transfers
          command: set-env academy-transfers-api AAD:TenantId ${{ secrets.AAD_TenantId }}
      - name: Deploy Code
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api: https://api.london.cloud.service.gov.uk
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: dfe
          cf_space: academy-transfers
          command: push -f TRAMS-API/manifest.yml -p TRAMS-API 
